### PR TITLE
update to 1.0.0rc0

### PR DESCRIPTION
**Pull request by phildong**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by phildong** [comment]
OK so the builds are failing because it can't find the package `medpy`, which is not available in `conda-forge` but only in `bioconda`.
I can reproduce this error locally with default channel settings, but once I manually add the `simpleitk` and `bioconda` channel in my build environment, the build succeeds.
This, however, should be handled by changing the channels settings in `conda-forge.yml`, as documented [here](https://conda-forge.org/docs/maintainer/conda_forge_yml.html#channels), but apparently it's not working as expected.
Any ideas?

**Comment by phildong** [comment]
Hey @mariusvniekerk just want to see if you have any expert insight about this? Please let me know what you think!

**Comment by phildong** [comment]
so I make sure everything can be installed from conda-forge except `medpy`. I gave up conda-installing that and fall-back to pip post-link scripts.
There is also this: https://github.com/bioconda/bioconda-recipes/pull/28229 that would make things much easier, but we'll see whether that happens in time.

**Comment by phildong** [comment]
@zsinnema any idea why the windows build keeps failing?

I also noticed same behavior when you pushed that "empty" commit: ce254816b3ee5cda5e8417ee2a4b97830a1c8924
any idea why that failed?

**Comment by zsinnema** [comment]
> @zsinnema any idea why the windows build keeps failing?
> 
> I also noticed same behavior when you pushed that "empty" commit: [ce25481](https://github.com/conda-forge/minian-feedstock/commit/ce254816b3ee5cda5e8417ee2a4b97830a1c8924)
> any idea why that failed?

@phildong I see the last win build are okay. I assume this is an "old" question and that this is solved

**Comment by phildong** [comment]
@zsinnema  well I'd still like to know exactly which dependency is causing the conflicts in windows build so we can keep an eye on it in the future, but I guess now we know it's one of the packages changed in 3ea2307.
Looking good to merge?

**Comment by zsinnema** [comment]
lgtm

**Pull request merged**
